version: "3"

services:
    database-findbase:
        container_name: database-findbase
        build:
            context: ./
            dockerfile: ./docker/postgresql/Dockerfile
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-findbase}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
            POSTGRES_USER: ${POSTGRES_USER:-findbase}
        ports:
            - "5432:5432"
        volumes:
            - db-findbase:/var/lib/postgresql/data:rw
    node:
        container_name: node-findbase
        user: node
        build:
            context: ./
            dockerfile: ./docker/node/Dockerfile
        command: npm run dev
        volumes:
            - ./:/home/node/web
            - /home/node/web/node_modules
        ports:
            - "3000:3000"
        environment:
            - DATABASE_URL=postgres://${POSTGRES_USER:-findbase}:${POSTGRES_PASSWORD:-password}@database-findbase/${POSTGRES_DB:-findbase}
        depends_on:
            - database-findbase

volumes:
    # postgres data
    db-findbase:
