export const INTEREST_TYPES = [
    "supermarket",
    "gym",
    "laundromat",
    "cafe",
    "coworking space",
];

export const LANGUAGES = [
    "es",
    "de",
    "fr",
    "pt",
    "it",
    "no",
    "sv",
    "fi",
    "et",
    "lv",
    "lt",
    "pl",
    "cs",
    "sk",
    "hu",
    "ro",
    "bg",
    "mk",
    "sq",
    "bs",
    "hr",
    "sl",
    "tr",
    "el",
    "he",
    "ar",
    "th",
    "vi",
    "zh",
    "ms",
    "id",
    "ko",
    "ja",
];

export interface IInterest {
    name: string;
    i18n: { [key in (typeof LANGUAGES)[number]]: string };
}

export const INTERESTS: Array<IInterest> = [
    {
        name: "supermarket",
        i18n: {
            es: "supermercado",
            de: "Supermarkt",
            fr: "supérette",
            pt: "supermercado",
            it: "supermercato",
            no: "supermarked",
            sv: "supermarket",
            fi: "supermarketki",
            et: "supermarket",
            lv: "supermārkte",
            lt: "supermārtė",
            pl: "supermarket",
            cs: "supermarket",
            sk: "supermarketa",
            hu: "szupermarket",
            ro: "supermarket",
            bg: "супермаркет",
            mk: "супермаркет",
            sq: "supermarketi",
            bs: "supermarket",
            hr: "supermarket",
            sl: "supermarket",
            tr: "süpermarket",
            el: "σούπερμαρκετ",
            he: "סוּפֶּרמַרקֶט",
            ar: "سوبر ماركت",
            th: "ซูเปอร์มาร์เก็ต",
            vi: "siêu thị",
            zh: "超市",
            ms: "pasarraya",
            id: "supermarket",
            ko: "슈퍼마켓",
            ja: "スーパーマーケット",
        },
    },
    {
        name: "gym",
        i18n: {
            es: "gimnasio",
            de: "fitnessstudio",
            fr: "salle de sport",
            pt: "academia o ginásio",
            it: "palestra",
            no: "treningsstudio",
            sv: "gym",
            fi: "kuntosali",
            et: "jõusaal",
            lv: "sporta zāle",
            lt: "sporto salė",
            pl: "siłownia",
            cs: "posilovna",
            sk: "zdravotvorná hala",
            hu: "konditerem",
            ro: "sală de sport",
            bg: "фитнес зала",
            mk: "теретана",
            sq: "palestër",
            bs: "teretana",
            hr: "teretana",
            sl: "fitnes",
            tr: "spor salonu",
            el: "γυμναστήριο",
            he: "חדר כושר",
            ar: "صالة رياضية",
            th: "ฟิตเนส",
            vi: "phòng tập gym",
            zh: "健身房",
            ms: "gim",
            id: "gym",
            ko: "헬스장",
            ja: "ジム",
        },
    },
    {
        name: "laundromat",
        i18n: {
            es: "lavandería",
            de: "Waschsalon",
            fr: "laverie",
            pt: "lavandaria",
            it: "lavanderia a gettoni",
            no: "vaskeri",
            sv: "tvättinrättning",
            fi: "itsepalvelupesula",
            et: "pesumaja",
            lv: "veļas mazgātava",
            lt: "skalbykla",
            pl: "pralnia samoobsługowa",
            cs: "prádelna",
            sk: "práčovňa",
            hu: "mosoda",
            ro: "spălătorie",
            bg: "обществена пералня",
            mk: "перална",
            sq: "lavanderi",
            bs: "praonica rublja",
            hr: "praonica rublja",
            sl: "pralnica",
            tr: "çamaşırhane",
            el: "πλυντήριο",
            he: "מכבסה",
            ar: "مغسلة",
            th: "ร้านซักผ้าหยอดเหรียญ",
            vi: "tiệm giặt ủi",
            zh: "自助洗衣店",
            ms: "kedai dobi",
            id: "laundromat",
            ko: "세탁소",
            ja: "コインランドリー",
        },
    },
    {
        name: "cafe",
        i18n: {
            es: "café",
            de: "Café",
            fr: "café",
            pt: "café",
            it: "caffè",
            no: "kafé",
            sv: "kafé",
            fi: "kahvila",
            et: "kohvik",
            lv: "kafejnīca",
            lt: "kavinė",
            pl: "kawiarnia",
            cs: "kavárna",
            sk: "kaviareň",
            hu: "kávézó",
            ro: "cafenea",
            bg: "кафене",
            mk: "кафе",
            sq: "kafene",
            bs: "kafić",
            hr: "kafić",
            sl: "kavarna",
            tr: "kafe",
            el: "καφετέρια",
            he: "בית קפה",
            ar: "مقهى",
            th: "ร้านกาแฟ",
            vi: "quán cà phê",
            zh: "咖啡馆",
            ms: "kafe",
            id: "kafe",
            ko: "카페",
            ja: "カフェ",
        },
    },
    {
        name: "coworking space",
        i18n: {
            es: "espacio de coworking",
            de: "Coworking-Space",
            fr: "espace de coworking",
            pt: "espaço de coworking",
            it: "spazio di coworking",
            no: "coworking-space",
            sv: "coworking-space",
            fi: "yhteistyötila",
            et: "ühiskontori ruum",
            lv: "kopstrādes telpa",
            lt: "bendradarbystės erdvė",
            pl: "przestrzeń coworkingowa",
            cs: "coworkingový prostor",
            sk: "coworkingový priestor",
            hu: "közösségi iroda",
            ro: "spațiu de coworking",
            bg: "споделено работно пространство",
            mk: "простор за заедничко работење",
            sq: "hapësirë pune e përbashkët",
            bs: "coworking prostor",
            hr: "coworking prostor",
            sl: "coworking prostor",
            tr: "ortak çalışma alanı",
            el: "χώρος συνεργασίας",
            he: "חלל עבודה משותף",
            ar: "مساحة عمل مشتركة",
            th: "พื้นที่ทำงานร่วมกัน",
            vi: "không gian làm việc chung",
            zh: "联合办公空间",
            ms: "ruang kerja bersama",
            id: "ruang kerja bersama",
            ko: "공유 오피스",
            ja: "コワーキングスペース",
        },
    },
];
